on: [push,workflow_dispatch]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to try my action
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2 
    - name: launch the RKNN toolkit2 action
      id: rknntk
      uses: changtimwu/hello-dkaction@v6
      with:
        wkdir: 'mynet'
    - name: Archive RKNN artifacts
      uses: actions/upload-artifact@v2
      with:
        name: rknn-model
        path: |
          mynet/*.rknn
    - name: Get the output
      run: |
       echo "GITHUB_WORKSPACE=$GITHUB_WORKSPACE"
       ls -al ${GITHUB_WORKSPACE}/mynet
       echo "The time was ${{ steps.rknntk.outputs.time }}"
       echo "The CPU info was ${{ steps.rknntk.outputs.cpuinfo }}"
