on: [push,workflow_dispatch]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    container: ghcr.io/changtimwu/rknn-toolkit2:features-docker
    name: A job to observe the image
    steps:
    - name: show some basics
      run: |
          pwd
          uname
          env
    - name: get file list
      run: |
          ls -alR /root/
          echo "done"

