on: [push,workflow_dispatch]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    container: ghcr.io/changtimwu/rknn-toolkit2:features-docker
    name: A job to test something
    steps:
    - name: just do ls
      id: proc1
      run: |
          echo "before ls"
          ls
          echo "after ls"

