on: [push,workflow_dispatch]

jobs:
  hello_world_job:
    runs-on: ghcr.io/changtimwu/rknn-toolkit2:features-docker
    name: A job to say hello
    steps:
     # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
